### ISSUE TITLE
NMM 62.21 crash after uninstalling/deactivating a mod "diagonally crossed circle"

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#135]
After uninstalling a mod via the diagonally crossed circle in mods tab (for easy reinstalling) NMM crashed. Trace Log attached.

[TraceLog20160704142802.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/346868/TraceLog20160704142802.txt)

**Comment by KunoMochi** [comment]
Error message:
`Der Prozess kann nicht auf die Datei "G:\Games\Nexus Mod Manager\Fallout4\Mods\ModProfiles\2oidd2gw\modlist.xml" zugreifen, da sie von einem anderen Prozess verwendet wird.`

Translated:
`The process can not access the file "C:\Games\Nexus Mod Manager\Fallout4\mods\ModProfiles\2oidd2gw\modlist.xml" access, because it is used by another process.`

Is another program currently using the modlist.xml file? Possibly NMM itself doing something else with the profile at the moment?

Does it keep doing it when you retry? Does it come up again even after restarting NMM?

**Comment by DuskDweller** [comment]
We're releasing a tentative fix for this with the next update.

**Comment by DuskDweller** [comment]
Should be fixed in version 0.62.22 .
