### ISSUE TITLE
Restoring Profile

### ISSUE THREAD

**Issue by Tyerial12** [Nexus-Mods/NMM-Test-Builds#23]
I had my profile backuped and went to restore it and NMM crashed
[TraceLog20160424171841.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/235729/TraceLog20160424171841.txt)

**Comment by KunoMochi** [comment]
Error message
`Invalid URI: The hostname could not be parsed.`

**Comment by roamwild** [comment]
Clicked the Revert (circular arrow) button next to a profile which I had uploaded, then changed
[TraceLog20160426011930.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/235935/TraceLog20160426011930.txt)
Trace file has been created: TraceLog20160426011930.txt
Mod Manager Version: 0.62.2.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
    CDF SP 0
    v2.0.50727 SP 2
    v3.0 SP 2
    v3.5 SP 1
    v4 SP 0
    v4.0 SP 0
    v4.5: 4.6 or later
Tracing is forced: False

Tracing an Unhandled Exception:
Exception: 
Message: 
    Invalid URI: The hostname could not be parsed.
Full Trace: 
    System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Nexus.Client.ModManagement.ProfileManager.DownloadProfile(String p_strPath, ConfirmActionMethod p_camConfirm, String p_strLabel)
   at Nexus.Client.ModManagement.UI.ProfileManagerVM.ProfileDownload(String p_strPath, ProfileManager p_pmProfileManager, String p_strLabel)
   at Nexus.Client.UI.Controls.ProfilesListView.Column_Click(Object sender, CellClickEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnCellClick(CellClickEventArgs args)
   at BrightIdeasSoftware.ObjectListView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by Tyerial12** [comment]
[TraceLog20160428005702.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239897/TraceLog20160428005702.txt)
the green circle arrow near the authors name "revert profile" seems to crash nmm then delete my profiles

**Comment by roamwild** [comment]
0.62.3
[TraceLog20160428223106.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/241713/TraceLog20160428223106.txt)

System.IO.IOException: The process cannot access the file 'C:\Users******\AppData\Local\Fallout4\plugins.txt' because it is being used by another process.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

Switched to blank local profile named 'offline' 
Downloaded my 'FO4 Mechanics and UI e' from Nexus 
https://www.nexusmods.com/fallout4/profiles/2640/

invalid key 3x
4th time success, 
local FO4 Mechanics and UI e(Backed9) created

switch to local FO4 Mechanics and UI e(Backed9) from main toolbar
'...Files missing, do you want to install...'
YES

double Tracelog crash with WER appcrash after first Tracelog prompt ends Nexusclient.exe

System.IO.IOException: The process cannot access the file 'C:\Users******\AppData\Local\Fallout4\plugins.txt' because it is being used by another process.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

//////////    Windows Eror Report Paste     ////////// 

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: NexusClient.exe
  Problem Signature 02: 0.62.5.0
  Problem Signature 03: 57224749
  Problem Signature 04: mscorlib
  Problem Signature 05: 4.6.1076.0
  Problem Signature 06: 56d79d90
  Problem Signature 07: 326
  Problem Signature 08: 10
 Problem Signature 09:  System.InvalidOperationException
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    1033
  Additional Information 1: de0a
  Additional Information 2: de0a4a85518e21a4803496f9a22bfe9c
  Additional Information 3: 24d6
  Additional Information 4: 24d63739bc51aac493b5fb6481638736

**Comment by DuskDweller** [comment]
IOException fixed in the next release, all other issues were fixed in previous patches.
