### ISSUE TITLE
NMM 62.3 installation of online profile, crash while restoring previous local profil

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#35]
adult test profile by IamTiz

Download and installation of profile with NMM 62.3:

Body Slide outfit studio has a fomod installer and contains a RaceMenuMorphsUUNP.esp and RaceMenuMorphsCBBE.esp. None of them was listed in the plugins tab after automatical installation by NMM 62.3 (as a file not present on my system).
Two files of my previous personal profile (but not part of the downloaded profile) were not disabled.
See image.

NMM crashed as I tried to restore my own/previous local profile. See Trace Log.
This profile now is lost/cannot be restored. My online profile/backup as uploaded could be automatically restored (now marked as „Backed 1“) after restart of NMM.
image:
![01 profile download installation](https://cloud.githubusercontent.com/assets/18660199/14892242/37cf31f4-0d6a-11e6-9db7-99bddbdaafb2.jpg)

Trace Log:
[TraceLog20160428133626.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/240899/TraceLog20160428133626.txt)

**Comment by roamwild** [comment]
`System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\lucz\AppData\Local\Skyrim\plugins.txt" zugreifen, da sie von einem anderen Prozess verwendet wird.`

`System.IO.IOException: The process cannot access the file 'C:\Users\******\AppData\Local\Skyrim\plugins.txt' because it is being used by another process.`

**Have not personally had corruption of local files** but multiple instances of this exception are also reported here:

Issue https://github.com/Nexus-Mods/NMM-Test-Builds/issues/24
Tracelogs from this post #24:
- [TraceLog20160426021401.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/236010/TraceLog20160426021401.txt)
- [TraceLog20160427190814.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239548/TraceLog20160427190814.txt)
- [TraceLog20160428005946.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239854/TraceLog20160428005946.txt)

Another user reported loss of local profile data here:
Issue https://github.com/Nexus-Mods/NMM-Test-Builds/issues/23 

> Tyerial12 commented 10 hours ago
> [TraceLog20160428005702.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/239897/TraceLog20160428005702.txt
> `System.UriFormatException: Invalid URI: The hostname could not be parsed.`
> 
> the green circle arrow near the authors name "revert profile" seems to crash nmm then delete my profiles

**Comment by DuskDweller** [comment]
The crash is fixed in the next release (0.62.8 )
