### ISSUE TITLE
currently available files on Nexus are displayed as not available in uploaded profile

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#46]
Current profile displays few mods as not being available, although I downloaded them few days ago and last night (sound, ambient sound mods, blacksmith forge trunch). See image:
![file display in profile](https://cloud.githubusercontent.com/assets/18660199/14932193/ff34c3d6-0e72-11e6-9f9c-f02ef8e5d465.jpg)

**Comment by AraFox** [comment]
Chiming in here because I had this same issue with 62.3 and still have it with this build. Having restored my computer with a fresh install of Skyrim and NMM and using my Nexus backup which claims this mod is unavailable, it still downloaded, installed, and activated it. 

link to 62.3 issue: https://github.com/Nexus-Mods/NMM-Test-Builds/issues/30

**Comment by DuskDweller** [comment]
Please do not delete profiles used to submit bugs report :(

Are you still experiencing this issue?

**Comment by DuskDweller** [comment]
Please let me know if you still have that kind of issues with profiles uploaded using 0.62.10 .

**Comment by DuskDweller** [comment]
Considering this as closed.
