### ISSUE TITLE
Several mods shown as missing online

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#80]
http://www.nexusmods.com/fallout4/profiles/3645/?tb=description&pUp=1

Shows 9 files missing. But only 2 files have yellow triangles in the download ID column, all others have numerical values.
I did run "Get missing/outdated download IDs" before uploading the profile.

**Comment by h-lucz** [comment]
Same here eg. for Skyrim. The corresponding files have not Download ID in NMM. A Download ID search with tool "Gets missing mod info" cannot be run, because the mod name in "Information" is not displayed (posted on github recently).
![allegedly missing mods](https://cloud.githubusercontent.com/assets/18660199/15225349/628e656c-187e-11e6-803c-53e81eaa126f.png)

**Comment by AraFox** [comment]
I'm not sure mine is entirely related, but it has the same symptom of an available mod shown as missing. It's actually a hotfix for another mod, and is located on the same file download page.

Differences: v62.14 and there is no missing ID for the [hotfix](http://www.nexusmods.com/skyrim/mods/24909/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodfiles%2F%3Fid%3D24909&pUp=1)

![hotfix](https://cloud.githubusercontent.com/assets/18659713/15356699/fa352924-1cbf-11e6-98b1-3a135d3c00e5.jpg)
![profile](https://cloud.githubusercontent.com/assets/18659713/15356701/fc19e00e-1cbf-11e6-863d-bf2444f9e90e.jpg)

**Comment by DuskDweller** [comment]
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.
