### ISSUE TITLE
Mod Manager visual scaling

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [Nexus-Mods/NMM-Test-Builds#98]
![nmm visual of scrunching](https://cloud.githubusercontent.com/assets/18717349/15405179/d2def368-1dce-11e6-8575-6d34f61587a7.jpg)

Lower left corner of picture. This actually does this when it is 1/4 or less than 1/4 of size. Not 1/2 like I had said before. I am assuming Alisa is using it this way to have the website, NMM & 1 or 2 other windows open to all fit. I would also like to add that if you do split screen with the NMM & NMM website and click a mod to download, it changes the size of NMM to smaller than split screen size.

**Comment by KunoMochi** [comment]
**Additional note:**
Adding to this, maybe you can have the status info about plugins, mods, and profiles be contextual, depending on which tab is currently in focus. That would clear up the status bar clutter a bit.

The download speed meter could probably be relocated as well, maybe integrated into the Download Manager or removed (since the Download Manager already displays the download speed).

I'm not sure about the Mod Activation Queue info in the status bar. On the one hand, it is informative, but on the other, maybe a small colored icon (or icons) indicating whether or not it is idle, active, or has an error.

Below is an example of how wide the window has to be to see everything when it is full.
![nmm0-62-14_statusbarclutter](https://cloud.githubusercontent.com/assets/7691651/15410980/d50e9230-1dea-11e6-90a9-2a91e0300912.png)

**Comment by DontBlnkBadWolf** [comment]
@KunoMochi that is why I have requested the choice for removal of a tab like "Download Date" or anything you want to remove. I think I will add another request of what you are talking about, but maybe it "Flashes" or "Flashes" a different color for files that may have an error during the download process. There have been multiple times that I didn't know there was a problem or error on a kile unless I hovered over the "Download Manager" tab

**Comment by DuskDweller** [comment]
Thanks for your feedback, anyway I wanted to point out that this kind of requests should be posted on the main NMM Github page not the test one :)

https://github.com/Nexus-Mods/Nexus-Mod-Manager

**Comment by DontBlnkBadWolf** [comment]
@DuskDweller which I knew. As I said I was thinking about requesting that. I wasn't requesting it here, that would be silly of me if I did. My request I first mentioned on my post above is already on the request area.
